### NumPy: Functions & Modules [Homework]
> **
> **Write code only where it is shown to be written. Don't delete comments!**

1. Please test all the features mentioned in the video lecture and try to understand them.
Some functions contain arguments, please experiment with them.

In [37]:
import numpy as np

In [38]:
# numpy.zeros

np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
help(np)

Help on package numpy:

NAME
    numpy

DESCRIPTION
    NumPy
    =====
    
    Provides
      1. An array object of arbitrary homogeneous items
      2. Fast mathematical operations over arrays
      3. Linear Algebra, Fourier Transforms, Random Number Generation
    
    How to use the documentation
    ----------------------------
    Documentation is available in two forms: docstrings provided
    with the code, and a loose standing reference guide, available from
    `the NumPy homepage <https://numpy.org>`_.
    
    We recommend exploring the docstrings using
    `IPython <https://ipython.org>`_, an advanced Python shell with
    TAB-completion and introspection capabilities.  See below for further
    instructions.
    
    The docstring examples assume that `numpy` has been imported as ``np``::
    
      >>> import numpy as np
    
    Code snippets are indicated by three greater-than signs::
    
      >>> x = 42
      >>> x = x + 1
    
    Use the built-in ``help`` functi

In [40]:
# numpy.ones
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# numpy.full
np.full((2,2), 0)

array([[0, 0],
       [0, 0]])

In [42]:
# numpy.eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
# numpy.arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
for i in [1,1,1,1,1]:
    i + 10

In [74]:
# numpy.add
list1 = [1,1,1,1,1]
np.add(list1, 10)

array([11, 11, 11, 11, 11])

In [46]:
# numpy.subtract
list2 = [1,1,1,1,1]
np.subtract(list2, 10)

array([-9, -9, -9, -9, -9])

In [47]:
# numpy.sin
np.sin(90)

0.8939966636005579

In [48]:
# numpy.multiply
np.multiply(list2, 10)

array([10, 10, 10, 10, 10])

In [49]:
# numpy.sqrt
np.sqrt((10,16,25))

array([3.16227766, 4.        , 5.        ])

In [50]:
np1 = np.array([1,3,4,5])
np2 = np.sqrt(np1)
np2

array([1.        , 1.73205081, 2.        , 2.23606798])

In [51]:
# numpy.dot
np.dot(np1, np2)

25.37649231020558

In [52]:
# numpy.sum
np.sum(np.arange(1,11))

55

In [53]:
# numpy.zeros_like
np.zeros_like(np1)

array([0, 0, 0, 0])

In [54]:
np1

array([1, 3, 4, 5])

In [55]:
# numpy.empty_like
np.empty_like(np1)

array([ 538976288, 1931501856, 1701863784, 1634235424])

In [56]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [57]:
# numpy.reshape
np.reshape(np.array([[1,2,3],[4,5,6]]), (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# numpy.reshape
np.reshape(np.array([[1,2,3],[4,5,6]]), (1,6))

array([[1, 2, 3, 4, 5, 6]])

In [59]:
np_w_nan = np.array([1,2,np.nan,4])
np_w_nan

array([ 1.,  2., nan,  4.])

## Logic indices

In [77]:
# numpy.isnan
logic1 = np.isnan(np.array([np_w_nan]))
logic1[0]

array([False, False,  True, False])

In [80]:
np_w_nan[~logic1[0]]

array([1., 2., 4.])

2. Please test all the functions of the ```numpy.random``` module mentioned in the video lecture and try to understand them.
Some functions contain arguments, please experiment with them.

In [111]:
# numpy.random.sample
logic_1 = np.array([1,2,3,4,5,6,7])
logic_1 

array([1, 2, 3, 4, 5, 6, 7])

In [105]:
np.random.sample(logic_1)

array([[[[[[[9.95400699e-01, 2.95059770e-01, 7.37445694e-01, ...,
             8.68523238e-01, 6.55094339e-01, 9.52884568e-01],
            [2.06121695e-01, 6.19688352e-01, 1.72366868e-01, ...,
             8.12607082e-01, 9.20706145e-01, 2.39713179e-01],
            [9.47131492e-01, 4.15014209e-01, 5.05025864e-01, ...,
             1.03443104e-01, 6.19720264e-01, 5.67582528e-01],
            [3.33001831e-02, 6.54721843e-01, 1.47327119e-01, ...,
             1.90278234e-01, 2.63469193e-01, 8.36123393e-01],
            [7.66122539e-01, 4.26396292e-01, 2.95941731e-01, ...,
             5.68169473e-01, 9.34428660e-02, 9.16180902e-01],
            [5.58330278e-01, 5.53737724e-01, 8.14082086e-01, ...,
             4.30810310e-01, 3.18414288e-01, 1.45127053e-01]],

           [[5.05440831e-02, 5.38549170e-01, 4.27391791e-01, ...,
             8.64320375e-01, 2.62900547e-01, 3.90280020e-01],
            [1.26981888e-01, 8.96669920e-01, 4.99356344e-01, ...,
             3.55934790e-01, 9.53497

In [119]:
# numpy.random.random
a = np.array([1,2,5,6,7,8,12])
a


array([ 1,  2,  5,  6,  7,  8, 12])

In [120]:
np.random.random(a)

array([[[[[[[3.21045508e-01, 1.02362001e-01, 6.38333934e-01, ...,
             3.32186586e-02, 9.89127105e-01, 4.77679177e-01],
            [9.38877315e-01, 9.38478812e-01, 5.27750127e-01, ...,
             9.00233395e-01, 6.52113797e-01, 8.83562684e-01],
            [5.97198805e-01, 7.21554607e-01, 4.75582359e-01, ...,
             1.32631103e-01, 2.88859734e-01, 7.14904614e-02],
            ...,
            [9.71940547e-01, 8.28893807e-01, 7.77517660e-01, ...,
             9.73788377e-01, 6.71130386e-01, 6.66102506e-02],
            [9.81357988e-01, 4.99051486e-01, 5.48385323e-01, ...,
             8.80076555e-02, 7.52333592e-01, 6.31076225e-01],
            [7.88126895e-01, 6.64621066e-01, 8.54751527e-01, ...,
             1.05312207e-01, 8.05601094e-01, 2.28449587e-01]],

           [[3.63264608e-02, 3.61550057e-01, 6.10743948e-01, ...,
             2.28125770e-01, 8.78779405e-01, 3.79390836e-01],
            [2.75907168e-01, 8.06375885e-01, 4.41747172e-02, ...,
             5.8342

In [133]:
# numpy.random.randint
gv = np.array([[1,4,5,9,12,5],[4,7,4,2,6,7]])
gv


array([[ 1,  4,  5,  9, 12,  5],
       [ 4,  7,  4,  2,  6,  7]])

In [135]:
np.random.randint(gv)

array([[0, 2, 2, 8, 8, 1],
       [2, 4, 0, 1, 1, 1]])

In [136]:
# numpy.random.random_integers
ubs = np.array([2,4,7])
ubs

array([2, 4, 7])

In [ ]:
np.random.random_integers(ubs)

In [144]:
# numpy.random.uniform
gh = np.array([2,4,7])
gh


array([2, 4, 7])

In [145]:
np.random.uniform(gh)

array([1.7599087 , 3.3704087 , 6.86263969])

In [150]:
# numpy.random.seed
bw = np.array([1,2,3,5,6,7,9])
bw


array([1, 2, 3, 5, 6, 7, 9])

In [151]:
np.random.seed(bw)

In [157]:
# numpy.random.shuffle
cdec = np.array([[2,4,5,6,8,1],[1,2,4,5,7,9]])
cdec


array([[2, 4, 5, 6, 8, 1],
       [1, 2, 4, 5, 7, 9]])

In [162]:
# numpy.random.permutation
np.random.permutation(cdec)


array([[2, 4, 5, 6, 8, 1],
       [1, 2, 4, 5, 7, 9]])

In [167]:
# numpy.random.choice
aad = np.array([[1,4,8,7],[2,5,7,8]])
aad


array([[1, 4, 8, 7],
       [2, 5, 7, 8]])

In [172]:
np.random.choice(aad)

ValueError: a must be 1-dimensional

# Great job!