In [1]:
import numpy as np

In [5]:
n = [[2,2],[-1,1]]
#n2 = [[2,2],[-1,1]]

In [17]:
array = np.array(n)
array_t = array.T

In [18]:
array_t

array([[ 2, -1],
       [ 2,  1]])

In [19]:
U, sigma, V =np.linalg.svd(array)

In [20]:
#U, sigma, V =np.linalg.svd(array_t)

In [21]:
print(f"Elements U: {U}")
print()
print(f"Elements sigma: {sigma}")
print()
print(f"Elements V: {V}")

Elements U: [[-1.00000000e+00  1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

Elements sigma: [2.82842712 1.41421356]

Elements V: [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## Validation:

In [30]:
def get_array(array, n):
    empty_array=np.zeros((n , len(array)))
    
    for i in range(len(array)):
        empty_array[i][i] = array[i]

    return empty_array


In [33]:
s=get_array(sigma, len(sigma))

In [ ]:
[2.82842712 1.41421356] -- > [[2.82842712 , 0
                               0, 1.41421356]]

In [36]:
result_array = np.dot(U, np.dot(s, V))
result_array

array([[ 2.,  2.],
       [-1.,  1.]])

### Another sample

In [37]:
x_test = [[2,-1], [3, 2], [5, -1],[-1, 2]]

In [38]:
U_test, sigma_test, V_test =np.linalg.svd(np.array(x_test))

In [43]:
print(f"Elements U: {U_test}")
print()
print(f"Elements sigma: {sigma_test}")
print()
print(f"Elements V: {V_test}")

Elements U: [[-0.3335869   0.25411179 -0.81420001  0.40152873]
 [-0.44353203 -0.73718167 -0.26353743 -0.43633765]
 [-0.80960368  0.15598689  0.5056555   0.25401277]
 [ 0.19115701 -0.60634847  0.10926518  0.7641084 ]]

Elements sigma: [6.2695369 3.1133434]

Elements V: [[-0.99480159  0.10183217]
 [-0.10183217 -0.99480159]]


In [44]:
s_test = get_array(sigma_test, len(x_test))
s_test

array([[6.2695369, 0.       ],
       [0.       , 3.1133434],
       [0.       , 0.       ],
       [0.       , 0.       ]])

In [41]:
x_test

[[2, -1], [3, 2], [5, -1], [-1, 2]]

In [46]:
np.dot(U_test, np.dot(s_test, V_test))

array([[ 2., -1.],
       [ 3.,  2.],
       [ 5., -1.],
       [-1.,  2.]])